DemoKaibay/Models/Auction.cs
using System.ComponentModel.DataAnnotations;

namespace DemoKaibay.Models
{
    public class Auction
    {
        public int Id { get; }

        [MaxLength(KaibayConsts.MaxTitleLength)]
        public string Title { get; set; }

        [MaxLength(KaibayConsts.MaxDescriptionLength)]
        public string Description { get; set; }

        public string? ImageUrl { get; set; }

        public string CreatorId { get; set; }

        public DateTime AuctionStarted { get; set; }

        public DateTime AuctionEnded { get; set; }

        [Required]
        public double InitialPrice { get; set; }

        public double CurrentPrice { get; set; }

        public double FinalPrice { get; set; }

        public ICollection<Bid> Bids { get; set; }

    }
}

DemoKaibay/Models/Bid.cs
namespace DemoKaibay.Models
{
    public class Bid
    {
        public int Id { get; set; }

        public int AuctionId { get; set; }

        public Auction Auction { get; set; }

        public string BuyerId { get; set; }

        public double Price { get; set; }

        public DateTime BidTime { get; set; }
    }
}

DemoKaibay/Models/ErrorViewModel.cs
namespace DemoKaibay.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoKaibay/Models/KaibayConsts.cs
namespace DemoKaibay.Models
{
    public class KaibayConsts
    {

        public const int MaxTitleLength = 32;

        public const int MaxDescriptionLength = 180;
    }
}

DemoKaibay/Controllers/AuctionController.cs
using DemoKaibay.Dtos;
using DemoKaibay.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DemoKaibay.Controllers
{
    [Authorize]
    public class AuctionController : Controller
    {
        private readonly DemoKaibayService kaibayService;

        public AuctionController(DemoKaibayService kaibayService)
        {
            this.kaibayService=kaibayService;
        }

        [HttpGet("Auction/Create")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateAuctionItemDto value)
        {
            await kaibayService.CreateAuction(value, User);

            await kaibayService.GetActiveAuctions();

            return Ok();
        }

        [HttpGet("Auction/{id}")]
        public async Task<IActionResult> Index(int id)
        {
            var auctionDetails = await kaibayService.GetAuctionDetails(id);
            return View(auctionDetails);
        }
    }
}

DemoKaibay/Controllers/HomeController.cs
using DemoKaibay.Models;
using DemoKaibay.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoKaibay.Controllers
{
    public class HomeController : Controller
    {
        private readonly DemoKaibayService itemService;

        public HomeController(DemoKaibayService itemService)
        {
            this.itemService=itemService;
        }

        public async Task<IActionResult> Index()
        {
            var activeAuctions = await itemService.GetActiveAuctions();
            return View(activeAuctions);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoKaibay/Views/Auction/Create.cshtml
@model DemoKaibay.Dtos.CreateAuctionItemDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CreateAuctionItemDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InitialPrice" class="control-label"></label>
                <input asp-for="InitialPrice" class="form-control" />
                <span asp-validation-for="InitialPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuctionEnded" class="control-label"></label>
                <input asp-for="AuctionEnded" class="form-control" />
                <span asp-validation-for="AuctionEnded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoKaibay/Views/Auction/Index.cshtml
@using DemoKaibay.Controllers
@model DemoKaibay.Dtos.AuctionDetailsDto

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div>
    <h4>AuctionDetailsDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InitialPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InitialPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CurrentPrice)
        </dt>
        <p class = "col-sm-10" id="price-@Model.Id">
            @Model.CurrentPrice
        </p>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuctionEnded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuctionEnded)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsEnded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsEnded)
        </dd>
    </dl>
</div>

<h2> Proposition </h2>
<div>
    <label for="say">Price</label>
    <input id="price" >
    <input type="button" id="sendButton" value="Send Bid" />
</div>


<div id="getting-started"></div>
@*<script type="text/javascript">
  $("#getting-started")
  .countdown("2022/09/09", function(event) {
    $(this).text(
      event.strftime('%D days %H:%M:%S')
    );
  });
</script>*@

<script src="~/js/kaibay.js" asp-append-version="true"></script>

DemoKaibay/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IList<DemoKaibay.Dtos.AuctionItemDto>

<div class="text-center">
    <h1 class="display-4">SignalR Auction</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core and SignalR</a>.</p>
</div>

<div class="card-deck">
  <div class="row">
        @foreach(var item in Model)
        {
            <div class="card" style="width: 18rem;">
              <img src="..." class="card-img-top mb-3 m-3 col-sm-6" alt="...">
              <div class="card-body">
                <h5 class="card-title">@item.Title</h5>
                <p class="card-text">@item.Description</p>
                <p class="card-text" id="price-@item.Id">@item.CurrentPrice</p>
                <p class="card-text">@item.AuctionEnded</p>
                <p class="card-text" data-countdown=@item.AuctionEnded></p>
                <a href="/Auction/@item.Id" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
        }
    </div>
</div>

<script src="~/js/site.js" asp-append-version="true"></script>

<script>
$('[data-countdown]').each(function() {
  var $this = $(this), finalDate = $(this).data('countdown');
  $this.countdown(finalDate, function(event) {
    $this.html(event.strftime('%D days %H:%M:%S'));
  });
});
</script>

DemoKaibay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoKaibay</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoKaibay.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.countdown/2.2.0/jquery.countdown.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.10/dist/sweetalert2.all.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoKaibay</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(@User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auction" asp-action="Create">Create Auction</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DemoKaibay - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>